### ISSUE TITLE
guidance for congrats/welcome vs Accessibility vs being left blank

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#267]
https://github.com/zencart/documentation/blob/master/content/user/new_user_topics/new_misc.md

If left blank (undefined or ''), both the Congratulations (h1) and Welcome (h2) defines will cause an Accessibility error as the system still displays the tags but, as empty.

Until we can come up with a way for the store to ignore the two if they are undefined, perhaps add a NOTE: just before the "Save" statement.

Something like:

NOTE:  Leaving this define blank ('') will result in an Accessibility validation error.

**Comment by drbyte** [comment]
Thanks for pointing this out.

I understand the point, and yet I'm reluctant to start a flood of documentation additions for every variation where someone could possibly cause a validation error.

Perhaps an even better solution is to come up with some suggested text/content that the storeowner should use instead. I imagine most who choose to "blank it out" just don't know what "should" go in that spot and they see the default placeholder as merely advertising/help text instead of as something they should put some thought into.

Is there some better suggestion we can offer instead, as I feel like this is more empowering to the reader than just "you'll have an Accessibility validation error" (which they won't know how (and sadly many won't care) to fix)?

**Comment by dbltoe** [comment]
The blank Welcome, can be turned off in Layout Settings but not the Congratulations.

**Comment by drbyte** [comment]
The "Congrats" text is intended to be changed to relevant content. Not merely turned off. It's an H1, which is a perfect SEO opportunity. They should use it. I wouldn't support adding any switch to turn it off.

**Comment by dbltoe** [comment]
As usual everything that's standard, isn't.  Things that should fluctuate, won't. etc.

It's probably a loosing battle trying to explain all the possibilities.  If one starts the main page with an h3 to maintain heading level, adds some pertinent text in the Congrats, and then decides to turn off the customer greeting -- they get dinged for the skip in level.

I keep trying to come up with some simple instructions that will get it into the store owners head without trigering the "I'm not gonna mess with that" attitude.

Unfortunately, it may never be able to be accomplished.  But, I did want to get it out there so greater minds could prevail.

**Comment by drbyte** [comment]
> I did want to get it out there so greater minds could prevail.

Yup. I posted some updates to encourage using it for SEO benefit instead of blanking it out in haste.
