### ISSUE TITLE
Reconcile Payment, Shipping and Order Total first pages

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#444]
If we want to move the content from the first page to _index.php (the way we did for payment), let's do it for all three.  Alternatively, possibly migrate this content to the _misc page.

**Comment by drbyte** [comment]
Observation:

The `_misc` pages are convenient as catch-alls for "I don't know where to put this" stuff. But that feels like something that should be temporary until a home is found for it. End-users will never think their question is "miscellaneous".

**Comment by drbyte** [comment]
I've done some shuffling for shipping and payment.

Still noodling on order-total stuff.

In all cases there was a list of "built in modules" that seemed to be the only/main reason for the (topic).md file.  So for Shipping I created a "built-in-modules" file for that content.  Considering the same for order-totals.
(For payment it's pretty much moot since there are multiple separate pages for each module, meaning the payment.md file didn't have anything necessary in it.)

**Comment by scottcwilson** [comment]
> End-users will never think their question is "miscellaneous".

If the search doesn't find their question in this file, they'll look there.  Worst case those files can be broken into one .md file per question; I just didn't have time to do it when i was setting things up.

**Comment by scottcwilson** [comment]
Yep, they do need to be broken up into individual files because of search (and listing on the All FAQs page).  Issue #453 created.

**Comment by scottcwilson** [comment]
Made these three look the same, added content, removed top level misc files.  (PayPal misc still remains - we could just add this to the PayPal page.
