### ISSUE TITLE
misc files must be broken into parts 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#453]
Putting several short questions in a misc file was done for expediency.  
However, there are problems with doing it this way:  

- Algolia doesn't break them into individual questions, so they don't show up on search. 
- They don't show up in the "All FAQs" page as separate questions
- No one thinks their question is "miscellaneous." 

Breaking each question from a misc file into a separate file will make them more visible. 

For questions that are just cross links (see XXX), use the redirect-only file structure shown in `user/admin/admin_password.md`

- [x] user/running/running_misc.md
- [x] user/products/products_misc.md
- [x] user/installing/installing_misc.md
- [x] user/ezpages/ezpages_misc.md
- [x] user/payment/paypal_misc.md
- [x] user/payment/payment_misc.md
- [x] user/template/template_misc.md
- [x] user/admin/admin_misc.md
- [x] user/troubleshooting/troubleshooting_misc.md
- [x] user/shipping/shipping_misc.md
- [x] user/search/search_misc.md
- [x] user/sideboxes/sidebox_misc.md
- [x] user/zen_cart_forum/forum_misc.md
- [x] user/new_user_topics/new_misc.md
- [x] user/first_steps/first_steps_misc.md
- [x] user/orders/orders_misc.md
- [x] user/order_total/order_total_misc.md
- [x] user/email/email_misc.md

**Comment by drbyte** [comment]
I wonder if now we're ending up with too many files that are all just links to other files?

**Comment by wiztechinc** [comment]
After spending the last 5 days or so going through the files and mapping them as I go, I am thinking that it's growing organically and not planned. Perhaps a top down look is appropriate right now? I got other issues about how this is done (like menus on desktop are hell to use). Got a good start here all due to Scott's work. Scott, do you have a master plan mapped out? I personally need that whether anyone else does or not. 

So the question is are all the pages with links necessary? Another question is, should the links only be the ones in the specific folder (cause they aren't always). If the topic is appropriate to the subject of the folder itself, why is it already somewhere else? Yes, many things are linked to other things because we are talking about a complicated program. How do we present this in an organized fashion that leads to easy access to material? And again, maybe we need to look at the menus. 

Just throwing thoughts at the wall here...

**Comment by scottcwilson** [comment]
> I wonder if now we're ending up with too many files that are all just links to other files?

This is done in a few places just to be sure that if you are in a folder, you still have relevant links to another folder.   Because not everyone will navigate with search, this ensures they are still seeing important content.

**Comment by scottcwilson** [comment]
> Scott, do you have a master plan mapped out? 

If you have extra time, it would be a huge help if you would work on completing some admin pages that need doing.  See #489.
