### ISSUE TITLE
Changing the 'Contribute to the docs' link

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#738]
Presumably the 'Contribute to the docs' link on the Docs homepage is aimed at first time contributors, so suggest changing it to point to [https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md](url) rather than [https://github.com/zencart/documentation](url) 

Happy to do a PR if approved.

**Comment by drbyte** [comment]
Did this come up because you found it difficult to find those instructions? 
If so, I just moved the CONTRIBUTING.md link higher up, so that it is found quicker.

I accept that one could argue that linking directly to CONTRIBUTING.md as you propose, is an ideal starting point.
.. because one can click the Issues or PullRequests tabs to begin making a content suggestion from there, just as well as from the repo home page.
... and therefore covers giving-instructions-to-newbies, and also still quick access to the repo for novices.

@scottcwilson I'm content with either approach. Feel free to go whichever way you think makes sense.

**Comment by simon1066** [comment]
> Did this come up because you found it difficult to find those instructions?

It was more a failure on my part to even think of looking for a Contributing or Readme file, I guess I jumped in too quickly.

If we were to link to a page other than the repo home then perhaps it should be to README.md instead of CONTRIBUTING.md

(In CONTRIBUTING.md, the README in 'the project's README file for' should be hyperlinked)

**Comment by drbyte** [comment]
> If we were to link to a page other than the repo home then perhaps it should be to README.md instead of CONTRIBUTING.md

The repo home also already displays the full README ... albeit below the list of top-level-directory files.

> (In CONTRIBUTING.md, the README in 'the project's README file for' should be hyperlinked)

I'm agreeable to that.

**Comment by simon1066** [comment]
> 
> 
> > If we were to link to a page other than the repo home then perhaps it should be to README.md instead of CONTRIBUTING.md
> 
> The repo home also already displays the full README ... albeit below the list of top-level-directory files.
> 
> > 
Darn, didn't see that. The link to the repo home works as is then.

**Comment by scottcwilson** [comment]
@simon1066 please create a PR or close as you think is best.
