### ISSUE TITLE
Big black blob at the bottom of the home page 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#921]
Can we tighten this up @dbltoe ?

**Comment by dbltoe** [comment]
As stated elsewhere, I can't seem to get at the file with edit permission even though I deleted every branch, fork, and repository.

Whenever I get cocky, I can just try to do something on GitHub and immediately get humbled.

Lines 79 thru 81 are the fundamental changes

 'footer {min-height:fit-content;}
.container-fluid {background-color: #403f4c}
#td-section-nav, main.col-12.col-md-9.col-xl-8.pl-md-5, .col-12.col-md-3.col-xl-2.td-sidebar.d-print-none, .td-main {background-color:#ffffff;}'

The fit-content cures the full page inside the documentation.
The #403f4c colors the container background the footer sits in.
The #ffffff is needed inside the site since the background is not set on the site pages.
The different terminology between main page and site pages results in the need to play with background colors in both areas.

**Comment by scottcwilson** [comment]
Fixed
